# NumPy 

NumPy (Numerical Python) is a Linear Algebra Library for Python and is one of the core packages for numerical computing in Python. It is used to process numbers or to calculate things with numbers.

## Why NumPy is important?
The reason it is so important for data analytics and data science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

Numpy is also incredibly fast, as it has bindings to C libraries. Pure Python processing numbers is slower compared to Numpy.

In reality, NumPy is not going to be used directly, but we will use pandas and matplotlib, which are working on top of NumPy.

For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

![numpy](https://camo.githubusercontent.com/f2feeac81e3c55f8daf75887a2c6041642496106ada557416cbb95d25cb9d599/68747470733a2f2f646f63732e676f6f676c652e636f6d2f64726177696e67732f642f652f32504143582d3176546b44744b594d5556647066566233545470725f387272567470616c32644f6b6e5555454f753835774a315269747a484866356e734a717a314f30536e5474384277674a6a78584d5958794971732f7075623f773d37323626683d333936)

We will only learn the basics of NumPy to get a clue of how NumPy works.

## Installation Instructions

Numpy can be installed with `pip`

    pip install numpy
    
If you can not install it, please refer to [Numpy's official documentation on various installation instructions.](https://numpy.org/install/)**

In [ ]:
!pip3 install numpy

In [2]:
!pip install matplotlib

     ---------------------------------------- 7.2/7.2 MB 14.9 MB/s eta 0:00:00
     ---------------------------------------- 164.1/164.1 kB ? eta 0:00:00
     ---------------------------------------- 3.3/3.3 MB 41.3 MB/s eta 0:00:00
     ---------------------------------------- 55.3/55.3 kB ? eta 0:00:00
     ------------------------------------- 960.8/960.8 kB 59.4 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. Some of the most important aspects of Numpy are **vectors, arrays, matrices**, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: **vectors** and **matrices**. Vectors are strictly *1-d arrays* and matrices are *2-d* (but you should note a matrix can still have only one row or one column).

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
a = [1, 2, 3]
b = ['abc', 'ddc']

In [6]:
np.array(a)

array([1, 2, 3])

In [7]:
np.array([6,7,8,9,10])

array([ 6,  7,  8,  9, 10])

Numpy arrays look like Python lists

mat เป็น list ซ้อน list แล้วแปลงเป็น array โดยใช้ np.array()

In [8]:
mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.arange(0, 15, 5)

array([ 0,  5, 10])

### zeros and ones

Generate arrays of zeros or ones

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [25]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [28]:
np.random.rand(5)

array([0.23617968, 0.60979128, 0.75490502, 0.17325735, 0.89212045])

In [29]:
np.random.rand(5,5)

array([[0.50143089, 0.49669508, 0.46823865, 0.21392116, 0.02515125],
       [0.82473965, 0.15651251, 0.1705461 , 0.96466261, 0.29789738],
       [0.51530534, 0.41984674, 0.04504724, 0.45796745, 0.33695369],
       [0.8367058 , 0.68707931, 0.83528287, 0.56334029, 0.50125333],
       [0.8423562 , 0.57954736, 0.80074252, 0.94988186, 0.2568276 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [30]:
np.random.randn(5)

array([-1.30730415,  0.24260843, -0.15170043, -0.49627438, -0.81260307])

In [32]:
np.random.randn(3,3)

array([[ 0.02284251,  0.72685132, -0.86128421],
       [-0.45565472,  1.26599299,  0.23409957],
       [-0.53588119, -0.30930357,  0.29354299]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [36]:
np.random.randint(1,100)

40

In [37]:
np.random.randint(1,100,10)

array([31, 58,  2, 60, 78, 18, 49, 48, 72, 65])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [38]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ran_a = np.random.randint(1,100,10)
ran_a

array([98, 14, 90, 34, 13, 63, 62, 50, 32, 87])

## Reshape
Returns an array containing the same data with a new shape.

In [43]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [45]:
ran_a.max()

98

In [46]:
ran_a.min()

13

In [47]:
ran_a.argmax()

0

In [49]:
ran_a.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

1D-Array

In [51]:
# Vector
a.shape

(25,)

In [53]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

2D-Array or Matrix

In [52]:
# Notice the two sets of brackets
a.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [54]:
a.reshape(1,25).shape

(1, 25)

In [55]:
a.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [56]:
a.reshape(25,1).shape

(25, 1)

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [58]:
A.shape

(2, 3)

In [59]:
A.ndim

2

In [60]:
A.size

6

3D-Array

In [61]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [62]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [63]:
B.shape

(2, 2, 3)

In [64]:
B.ndim

3

In [65]:
B.size

12

### Array Data Types: dtype

You can also grab the data type of the object in the array:

In [66]:
a.dtype

dtype('int32')

In [67]:
b = np.array([0, .5, 1.5, 2])

In [68]:
b.dtype

dtype('float64')

Convert integer to float

In [69]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [70]:
np.array([1, 2, 3], dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [71]:
c = np.array(['a', 'b', 'c'])

In [72]:
c.dtype

dtype('<U1')