# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [4]:
#Creating sample array
a = np.arange(0,11)

In [5]:
#Show
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [6]:
#Get a value at an index
a[5]

5

In [7]:
a[5], a[7], a[9]

(5, 7, 9)

In [8]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
#Get values in a range
a[3:7]  #range(3,7)

array([3, 4, 5, 6])

In [10]:
#Get values in a range
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a[::2]

array([ 0,  2,  4,  6,  8, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [12]:
a_list = [1, 2, 3]

In [15]:
a_list[0:3] = 10

TypeError: can only assign an iterable

In [16]:
a_list[0:3] = [10, 11, 12]

In [17]:
a_list

[10, 11, 12]

In [18]:
#Setting a value with index range (Broadcasting)
a[0:5] = 100

#Show
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
# Reset array, we'll see why I had to reset in a moment
a = np.arange(0, 11)

#Show
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#Important notes on Slices
slice_a = a[0:6]

#Show slice
slice_a

array([0, 1, 2, 3, 4, 5])

In [21]:
#Change Slice
slice_a[:] = 99

#Show Slice again
slice_a

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [22]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [23]:
#To get a copy, need to be explicit
a_copy = a.copy()
a_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
a_copy[:] = 555

In [26]:
a_copy

array([555, 555, 555, 555, 555, 555, 555, 555, 555, 555, 555])

In [25]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**.

In [27]:
a_2d = np.array((
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
))

a_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
#Indexing row
a_2d[1]


array([20, 25, 30])

In [29]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value: 2nd row, first element
a_2d[1][0]

20

In [30]:
# Getting individual element value
a_2d[1, 0]

20

In [31]:
a_2d[:, 1]

array([10, 25, 40])

In [34]:
# 2D array slicing
a_2d[0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [35]:
#Shape (2,2) from top right corner
a_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [36]:
#Shape bottom row
a_2d[-1]

array([35, 40, 45])

In [37]:
#Shape last column
a_2d[:,-1]

array([15, 30, 45])

In [38]:
a_2d[[2,0,1]]

array([[35, 40, 45],
       [ 5, 10, 15],
       [20, 25, 30]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [18]:
#Set up matrix


In [19]:
#Length of array


In [20]:
#Set up array


Fancy indexing allows the following

In [21]:
#Allows in any order


## Selection (Boolean)

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [39]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Regular Selection

In [40]:
a[0], a[5]

(1, 6)

Multi-index

In [41]:
a[[-1,0,5]]

array([10,  1,  6])

Boolean array

In [42]:
a[[True,False,False,True,False,True,True,False,False,True]]

array([ 1,  4,  6,  7, 10])

### Broadcasting boolean operations

In [43]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [44]:
bool_a = a > 4

In [45]:
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
a[a < 7]

array([1, 2, 3, 4, 5, 6])

In [48]:
x = 5
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
a.mean()

5.5

In [50]:
a[a > a.mean()]

array([ 6,  7,  8,  9, 10])

In [51]:
a[~(a > a.mean())]

array([1, 2, 3, 4, 5])

In [52]:
a[(a == 3) | (a == 1)] # OR

array([1, 3])

In [53]:
a[(a <= 8) & (a % 2 == 0)] # AND

array([2, 4, 6, 8])

In [54]:
A = np.random.randint(100, size=(3, 3))

In [55]:
A

array([[33, 74, 66],
       [34, 72, 43],
       [18, 79,  1]])

In [56]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [57]:
A[A > 30]

array([33, 74, 66, 34, 72, 43, 79])