# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

Operation between arrays and scalars

In [2]:
a_list = [1, 2, 3]
a_list + [10]

[1, 2, 3, 10]

In [3]:
[x+10 for x in a_list]

[11, 12, 13]

In [4]:
import numpy as np

In [5]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
a * 100 

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

Operation between arrays and arrays

In [8]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
a_list + a_list

[1, 2, 3, 1, 2, 3]

In [10]:
a * 2 * a

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [11]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
0/0

ZeroDivisionError: division by zero

In [12]:
# Warning on division by zero, but not an error!
# Just replaced with nan
a/a

C:\Users\LAB207_0\AppData\Local\Temp\ipykernel_14064\1356885574.py:3: RuntimeWarning: invalid value encountered in divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
# Also warning, but not an error instead infinity
1/a

C:\Users\LAB207_0\AppData\Local\Temp\ipykernel_14064\185669817.py:2: RuntimeWarning: divide by zero encountered in divide
  1/a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
a + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [18]:
a += 100
# a = a + 100

In [19]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

## Summary statistics

In [21]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [20]:
a.sum()

1045

In [22]:
a.mean()

104.5

In [23]:
a.std()

2.8722813232690143

In [24]:
a.var()

8.25

In [25]:
A = np.random.randint(100, size=(3, 3))

In [26]:
A

array([[56, 12, 19],
       [69, 35, 97],
       [69, 39, 19]])

In [27]:
A.sum()

415

In [28]:
A.mean()

46.111111111111114

In [29]:
A.std()

26.962708586508654

In [30]:
A.sum(axis=0)

array([194,  86, 135])

In [31]:
A.sum(axis=1)

array([ 87, 201, 127])

In [32]:
A.mean(axis=0)

array([64.66666667, 28.66666667, 45.        ])

In [33]:
A.mean(axis=1)

array([29.        , 67.        , 42.33333333])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [35]:
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [34]:
#Taking Square Roots
np.sqrt(a)

array([10.        , 10.04987562, 10.09950494, 10.14889157, 10.19803903,
       10.24695077, 10.29563014, 10.34408043, 10.39230485, 10.44030651])

In [36]:
#Calcualting exponential (e^)
np.exp(a)

array([2.68811714e+43, 7.30705998e+43, 1.98626484e+44, 5.39922761e+44,
       1.46766223e+45, 3.98951957e+45, 1.08446386e+46, 2.94787839e+46,
       8.01316426e+46, 2.17820388e+47])

In [37]:
np.max(a) #same as arr.max()

109

In [38]:
a.max()

109

In [39]:
np.sin(a)

array([-0.50636564,  0.45202579,  0.99482679,  0.62298863, -0.3216224 ,
       -0.97053528, -0.7271425 ,  0.18478174,  0.92681851,  0.81674261])

In [40]:
np.log(a)

array([4.60517019, 4.61512052, 4.62497281, 4.63472899, 4.6443909 ,
       4.65396035, 4.66343909, 4.67282883, 4.68213123, 4.69134788])